  **By: Gedamu A.**

  2020-20-01

  **Center for Future Media, UESTC, China** 

  


**Big Q ?**

why do we need a new tensor? why can not use basic numpy ? 


**Autograd : Automatic Diffeentiation**

Central to all neural networks in PyTorch is the autograd package. 

The autograd package provides automatic differentiation for all operations on Tensors. 
1. It is a define-by-run framework, which means that your backprop is defined by how your code is run, and
2. That every single iteration can be different

PyTorch used the class Variable to record gradients. You had to wrap Tensors in Variables. Variables behaved exactly like Tensors.

With  Tensor can record gradients directly if you tell it do do so, e.g. torch.ones(3, requires_grad=True). There is no need for Variable anymore. Many tutorials still use Variable, be aware!

Refs : 
*   https://pytorch.org/docs/stable/autograd.html
*   https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html

**packages:**
1. **torch.Tensor** ==> centeral class of the package, if you set its attribute **.requires_grad** as True, it starts to track all operations on it.
2. **.backward()** ==> When you finish your computation you can call  and have all the gradients computed automatically. The gradient for this tensor will be accumulated into .grad attribute.
3. **with torch.no_grad():** To prevent tracking history (and using memory), you can also wrap the code block in


**Note: **
This can be particularly helpful when evaluating a model because the model may have trainable parameters with requires_grad=True, but for which we don’t need the gradients.


There’s one more class which is very important for autograd implementation - a **Function**.

**Tensor** and **Function** are interconnected and build up an acyclic graph, that encodes a complete history of computation. Each tensor has a .grad_fn attribute that references a Function that has created the Tensor (except for Tensors created by the user - their grad_fn is None).

If you want to compute the derivatives, you can call **.backward()** on a Tensor. If Tensor is a scalar (i.e. it holds a one element data), you don’t need to specify any arguments to backward(), however if it has more elements, you need to specify a gradient argument that is a tensor of matching shape.



lets Do it .... cheer up !!!

In [3]:
# Create a tensor and set requires_grad=True to track computation with it
import torch 
from torch import autograd 

x = torch.ones(2, 2)
x

tensor([[1., 1.],
        [1., 1.]])

In [6]:
x = torch.ones(2, 2,  requires_grad =True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [7]:
y = x+2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

Y was created as a result of an opration, so it has grad_fun

In [8]:
print(y.grad_fn)

More opration here:  

In [10]:
z = y*y*4
out = z.mean()

print(z, out)

tensor([[36., 36.],
        [36., 36.]], grad_fn=<MulBackward0>) tensor(36., grad_fn=<MeanBackward0>)


Gradients: 
Let’s backprop now. Because out contains a single scalar, out.backward() is equivalent to **out.backward(torch.tensor(1.)).**

In [0]:
out.backward()

Print gradients d(out)/dx

In [12]:
print(x.grad)

tensor([[6., 6.],
        [6., 6.]])


 What is going to happen here?


In [14]:

# Don't record the gradient
# Useful for inference

params = torch.tensor(2., requires_grad=True)

with torch.no_grad():
    y = x * x
    print(x.grad_fn)

None



nn.Module and nn.Parameter keep track of gradients for you

In [19]:
import torch.nn as nn
lin = nn.Linear(2, 1, bias=1)
lin.weight

Parameter containing:
tensor([[0.4725, 0.4452]], requires_grad=True)

In [21]:
type(lin.weight)
len(lin.weight)

1

In [23]:
 # using .detach() to get a new Tensor with the same content but that does not require gradients:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)


**Exercise**

Do you remember the analytical solution to solve for the parameters of linear regression? Implement it.

But what About the GPU ?

In [0]:
if cuda:
  model = model.cuda()