**Prerequisites:**

*   you implemented machine learning models before using Pytorch 
*   you know what Deep learning is 
*   you have used numpy 
*   maybe you have used tensorflow or similar library
*   if you use Pytorch on a daily basis , this  workshop i sprobably not for you 








**Goal: **


*   Understand Pytorch 
*   Overview of all Concepts 
*   be able to use transfer Learning 
*   Know some handy tools and libs 





Before We Start :


*   Great to be here!
*   thanks for the contribution and coming! i own you Drink 
*   Set up 
1. Go to https://colab.research.google.com
2. Create a new python 3 notebook
3. Enable the GPU: "Edit -> Notebook settings -> Hardware accelerator: GPU -> Save"
4. then install pytorch : !pip install torch torchvision









In [6]:
 !pip install torch torchvision

 **Using PyTorch + GPU/TPU in Google's Colab:** Colaboratory is a Google research project created to help disseminate machine learning education and research. It's a Jupyter notebook environment that requires no setup to use and runs entirely in the cloud. Colaboratory notebooks are stored in Google Drive and can be shared just as you would with Google Docs or Sheets. Colaboratory is free. 



In [7]:
import torch 

print(torch.__version__)

device ="cuda" if torch.cuda.is_available() else "cpu"
print(device)

1.3.1
cuda


**Pytorch Overview** : what is Pytorch ? "**PyTorch** - Tensors and Dynamic neural networks in Python with strong GPU acceleration. PyTorch is a deep learning framework for fast, flexible experimentation."
It’s a Python-based scientific computing package targeted at two sets of audiences:
1. A replacement for NumPy to use the power of GPUs
2.Aa deep learning research platform that provides maximum flexibility and speed

-- https://pytorch.org/*

**Build by Run** - what is that and why do I care 
![alt text](https://drive.google.com/uc?id=1-oHRCr3sYK1lW3DbA-d4bmxTzm3w03ao)

this is much better explanation of pyTorch(I think)

In [8]:
import torch 
import pdb 

def fun(x):
  r = x+10
  return r
x = torch.randn(1,10)
print(fun(x))

tensor([[10.6230,  9.5442, 10.2941,  9.5125,  9.9402, 10.5118, 10.3894,  9.2257,
         10.2571,  8.5856]])


i like pytorch becouse 


1. It is just stupid python 
2. easy to debug 
3. research 
4. research is often published as pytroch project 



**Get Starting: Basic pytorch**

Tensor : Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

Tensor - the atoms of machine learning

In [9]:
import torch 
print("torch version ==>" + str(torch.__version__))
import torchvision 
print("torchvision version ==>"  + str(torchvision.__version__))
import numpy as np 
print("torch version ==>" + str (np.__version__))


torch version ==>1.3.1
torchvision version ==>0.4.2
torch version ==>1.17.5


In [0]:
import numpy as np
from numpy.linalg import inv
from numpy.linalg import multi_dot as mdot

In [11]:

# numpy
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [0]:
# torch
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [12]:
# numpy
X = np.random.random((5, 3))
X

array([[0.17202813, 0.76819027, 0.76828488],
       [0.48885661, 0.0033277 , 0.09142805],
       [0.39188935, 0.98670756, 0.46882752],
       [0.14916113, 0.22837405, 0.81944391],
       [0.65574279, 0.37329872, 0.38183443]])

In [13]:
# pytorch
Y = torch.rand((5, 3))
Y

tensor([[0.8695, 0.4345, 0.7424],
        [0.0311, 0.2317, 0.0108],
        [0.6855, 0.6742, 0.2524],
        [0.1267, 0.6404, 0.6670],
        [0.8834, 0.0451, 0.8135]])

In [14]:
X.shape

(5, 3)

In [15]:
Y.shape

torch.Size([5, 3])

In [16]:
# numpy
X.T @ X

array([[0.87439937, 0.79930976, 0.73320469],
       [0.79930976, 1.75522581, 1.38276689],
       [0.73320469, 1.38276689, 1.63570583]])

In [17]:
# torch
Y.t() @ Y

tensor([[2.0235, 0.9683, 1.6221],
        [0.9683, 1.1092, 0.9591],
        [1.6221, 0.9591, 1.7217]])

In [18]:
# numpy
inv(X.T @ X)

array([[ 2.03751829, -0.62376507, -0.38600844],
       [-0.62376507,  1.89661606, -1.3237285 ],
       [-0.38600844, -1.3237285 ,  1.90341752]])

**More on Pytorch**

In [19]:
A = torch.eye(3)
A.add(1)
#A.add_(1)

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])

Indexing and broadcasting: 
it works as expected like numpy 

In [20]:
A[0,0]
A
A[0:2]
A[0:]
A[2:]
A[-1]

tensor([0., 0., 1.])

Converting 

In [21]:
A = torch.eye(3)
A

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [22]:
# torch --> numpy
B = A.numpy()
B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

Note: torch and numpy can share the same memory / zero-copy

In [23]:
A.add_(.5)
A

tensor([[1.5000, 0.5000, 0.5000],
        [0.5000, 1.5000, 0.5000],
        [0.5000, 0.5000, 1.5000]])

In [24]:
B

array([[1.5, 0.5, 0.5],
       [0.5, 1.5, 0.5],
       [0.5, 0.5, 1.5]], dtype=float32)

In [25]:
# numpy --> torch
torch.from_numpy(np.eye(3))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=torch.float64)

More :

In [26]:
 [i for i in dir(torch) if not i.startswith("-")]

['AVG',
 'AggregationType',
 'Argument',
 'ArgumentSpec',
 'BFloat16Storage',
 'BFloat16Tensor',
 'BenchmarkConfig',
 'BenchmarkExecutionStats',
 'Block',
 'BoolStorage',
 'BoolTensor',
 'BoolType',
 'ByteStorage',
 'ByteTensor',
 'CharStorage',
 'CharTensor',
 'ClassType',
 'Code',
 'CompilationUnit',
 'CompleteArgumentSpec',
 'CudaBFloat16StorageBase',
 'CudaBoolStorageBase',
 'CudaByteStorageBase',
 'CudaCharStorageBase',
 'CudaDoubleStorageBase',
 'CudaFloatStorageBase',
 'CudaHalfStorageBase',
 'CudaIntStorageBase',
 'CudaLongStorageBase',
 'CudaShortStorageBase',
 'DictType',
 'DoubleStorage',
 'DoubleTensor',
 'ErrorReport',
 'ExecutionPlan',
 'ExtraFilesMap',
 'FatalError',
 'FileCheck',
 'FloatStorage',
 'FloatTensor',
 'FloatType',
 'Function',
 'FunctionSchema',
 'Future',
 'Generator',
 'Gradient',
 'Graph',
 'GraphExecutorState',
 'HalfStorage',
 'HalfStorageBase',
 'HalfTensor',
 'IODescriptor',
 'IntStorage',
 'IntTensor',
 'IntType',
 'JITException',
 'ListType',
 'Lock

**But what about the GPU?**
How do I use the GPU?

If you have a GPU make sure that the right pytorch is installed (check https://pytorch.org/ for details).

In [27]:
import torch
device ="cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda


You can move data to the GPU by doing .to(device). or .cuda()

In [28]:
data = torch.eye(3)
data.to(device)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], device='cuda:0')

Now the computation happens on the GPU.

In [29]:
res = data + data
res

tensor([[2., 0., 0.],
        [0., 2., 0.],
        [0., 0., 2.]])

In [30]:
res.device

device(type='cpu')